[package]
name = "learn-raylib"
version = "0.1.0"
authors = ["anticore <slimedev@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
raylib = "3.5"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
